### ISSUE TITLE
Version conflict between sources on github and files on repositories (Minor-Issue)

### ISSUE THREAD

**Issue by ghost** [panterch/org.vaadin.mvp#3]
The pom from github sources has the same version like the deployed jars on the repositories (0.9.0), but the content isn't identical for example BasePresenter.java.

By the way thanks for the greet work...

**Comment by mtam** [comment]
Shouldn't be an issue anymore (?). Please note that I'm not maintaining the vaadin addon repository stuff, but releases are available from the Maven Repository (now stated in the readme).
