### ISSUE TITLE
Unallocate view from Memory

### ISSUE THREAD

**Issue by vvaugelade** [panterch/org.vaadin.mvp#6]
Hi,

I'm using your Add-on in my Vaadin project. I was wondering if there was any way to avoid to stock the view in Memory. I'll explain:

When you navigate in the application, you use a view with components filled with some values (imagine a form the user have filled). Then you go away from the view replacing it by another one. But if you want to display the view again, you retrieve all the informations you had filled previously. Of course I can add a treatment to clear all components when my view is called but they are still allocate in memory. I would like to find a way to litteraly remove the instance of my view from the session and create a new one each time the view is called. 
I've seen a way of doing this by setting them to null and let the garbage collector do his job but I was wondering if a more elegant solution was existing.

**Comment by mtam** [comment]
Hi,

there are basically two options in order to get fresh view instances:
- a view is usually bound to a presenter instance, so if you create a new presenter instance for every access you should get a fresh and empty view as it's done in the example app [1]
- if you extend `FactoryPresenter` (like in the example here [2]) instead of `BasePresenter` you'll have access to the `createView()`-method to create fresh view copies.

``` java
class SomePresenter extends FactoryPresenter<V, E> {
  void onSomeEvent() {
    this.view = this.createView();
  }
}
```

Hope that helps!
1. https://github.com/panter/org.vaadin.mvp/blob/master/org.vaadin.mvp.example/src/main/java/com/example/menu/MenuPresenter.java
2. https://github.com/panter/org.vaadin.mvp/blob/master/org.vaadin.mvp.example/src/main/java/com/example/useradmin/UserAdminPresenter.java

**Comment by vvaugelade** [comment]
Hi,

Thank you for your answer which is very usefull to get a fresh view. I extend the Factory Presenter so the createView solution seems nice. But this will create a new instance of the view each time it is called and this instance won't be destroyed (if not setted to null) so kept in the session which will increase its size.

I think that calling the createView function at the beginning of the treatment and setting the view to null at the end would work and free some memory, but I was wondering if another solution was existing (as a destroyView function!)

As the session is on a server, creating new instances of the view each time without destroying the old one will soon create memory problem. 
At the moment I just keep one instance of the view runnning, instantiate its components in its constructor and call the removeAllComponents function when I don't need the view anymore. This way I still have the view instance but I have removed all its component instance from the memory when it is not used. When I call the view all the components are created again thanks to the constructor.

**Comment by mtam** [comment]
Hi again,

As I didn't look at the code for quite some time I'm not quite sure if I'm right, but I think that assigning a new view instance to the presenters `view` property should remove the reference to the old view instance and thus allowing the GC to collect it (unless there's a reference kept somewhere else in the application code).

However, I hope to find some time soon to have a closer look at it.

**Comment by vvaugelade** [comment]
I think you're right. I still need to remove the components of the running instance to "light" the session when the view is not in use but it's not such a pain. It was nice to learn about the createView function. Thanks!
